import type { ComponentSchema } from "@/lib/component-schema";

export const COMPONENT_REGISTRY: ComponentSchema[] = [
  {
    id: "hero-standard",
    name: "Hero Standard",
    category: "hero",
    description:
      "Primary hero component for service and solution pages with headline, copy and CTA.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["core", "high-visibility"],
    variants: [
      {
        id: "left-content-right-image",
        label: "Left Content / Right Image",
        description: "Split layout with content left and media right.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "centered",
        label: "Centered",
        description: "Centered hero for broader brand and campaign pages.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface", "tint"],
      },
    ],
    fields: [
      {
        id: "eyebrow",
        label: "Eyebrow",
        type: "text",
        placeholder: "Optional category label",
        validation: [{ type: "maxLength", value: 40 }],
        permissions: {
          canView: ["creator", "approver", "admin"],
          canEdit: ["creator", "approver", "admin"],
          canApprove: ["approver", "admin"],
          canPublish: ["admin"],
        },
        ai: {
          aiEditable: true,
          aiGenerate: true,
          aiRewrite: true,
          promptHint: "Keep concise and credibility-led.",
        },
        localisable: true,
      },
      {
        id: "headline",
        label: "Headline",
        type: "text",
        required: true,
        placeholder: "Primary headline",
        validation: [{ type: "maxLength", value: 70 }],
        permissions: {
          canView: ["creator", "approver", "admin"],
          canEdit: ["creator", "approver", "admin"],
          canApprove: ["approver", "admin"],
          canPublish: ["admin"],
        },
        ai: {
          aiEditable: true,
          aiGenerate: true,
          aiRewrite: true,
          promptHint: "Enterprise-grade, clear and non-hyped.",
        },
        localisable: true,
      },
      {
        id: "subheading",
        label: "Subheading",
        type: "textarea",
        required: true,
        placeholder: "Supporting paragraph",
        validation: [{ type: "maxLength", value: 180 }],
        permissions: {
          canView: ["creator", "approver", "admin"],
          canEdit: ["creator", "approver", "admin"],
          canApprove: ["approver", "admin"],
          canPublish: ["admin"],
        },
        ai: {
          aiEditable: true,
          aiGenerate: true,
          aiRewrite: true,
          promptHint: "Support the headline with clear detail and credibility.",
        },
        localisable: true,
      },
      {
        id: "primaryCtaLabel",
        label: "Primary CTA Label",
        type: "text",
        required: true,
        validation: [{ type: "maxLength", value: 28 }],
        permissions: {
          canView: ["creator", "approver", "admin"],
          canEdit: ["creator", "approver", "admin"],
          canApprove: ["approver", "admin"],
          canPublish: ["admin"],
        },
        ai: {
          aiEditable: true,
          aiGenerate: true,
          aiRewrite: true,
          promptHint: "Use approved CTA language only.",
        },
        localisable: true,
      },
      {
        id: "primaryCtaUrl",
        label: "Primary CTA URL",
        type: "url",
        required: true,
        validation: [{ type: "url" }],
        permissions: {
          canView: ["creator", "approver", "admin"],
          canEdit: ["creator", "approver", "admin"],
          canApprove: ["approver", "admin"],
          canPublish: ["admin"],
        },
        ai: {
          aiEditable: false,
          aiGenerate: false,
          aiRewrite: false,
        },
      },
      {
        id: "image",
        label: "Hero Image",
        type: "image",
        permissions: {
          canView: ["creator", "approver", "admin"],
          canEdit: ["creator", "approver", "admin"],
          canApprove: ["approver", "admin"],
          canPublish: ["admin"],
        },
        ai: {
          aiEditable: false,
          aiGenerate: false,
          aiRewrite: false,
        },
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "Primary high-visibility page component.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: ["hero-standard"],
      mustBeFirst: true,
      maxPerPage: 1,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: [
        "headline",
        "subheading",
        "primaryCtaLabel",
        "primaryCtaUrl",
      ],
      fieldMappings: [
        { sourceField: "eyebrow", targetField: "eyebrow" },
        { sourceField: "headline", targetField: "headline", required: true },
        { sourceField: "subheading", targetField: "subheading", required: true },
        {
          sourceField: "primaryCtaLabel",
          targetField: "primaryCtaLabel",
          required: true,
        },
        {
          sourceField: "primaryCtaUrl",
          targetField: "primaryCtaUrl",
          required: true,
        },
        { sourceField: "image", targetField: "image" },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "value-points-grid",
    name: "Value Points Grid",
    category: "content",
    description:
      "Structured value-point cards used to communicate service benefits or differentiators.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["core", "repeatable"],
    variants: [
      {
        id: "three-up",
        label: "3 Column Grid",
        description: "Three-card value point layout.",
        allowedLayouts: ["grid-3"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "four-up",
        label: "4 Column Grid",
        description: "Four-card value point layout.",
        allowedLayouts: ["grid-4"],
        allowedBackgrounds: ["white", "surface"],
      },
    ],
    fields: [
      {
        id: "sectionHeading",
        label: "Section Heading",
        type: "text",
        validation: [{ type: "maxLength", value: 70 }],
        permissions: {
          canView: ["creator", "approver", "admin"],
          canEdit: ["creator", "approver", "admin"],
          canApprove: ["approver", "admin"],
          canPublish: ["admin"],
        },
        ai: {
          aiEditable: true,
          aiGenerate: true,
          aiRewrite: true,
        },
        localisable: true,
      },
      {
        id: "items",
        label: "Value Points",
        type: "repeater",
        required: true,
        validation: [
          { type: "minItems", value: 3 },
          { type: "maxItems", value: 4 },
        ],
        permissions: {
          canView: ["creator", "approver", "admin"],
          canEdit: ["creator", "approver", "admin"],
          canApprove: ["approver", "admin"],
          canPublish: ["admin"],
        },
        ai: {
          aiEditable: true,
          aiGenerate: true,
          aiRewrite: true,
          promptHint: "Keep each value point concise, distinct and benefits-led.",
        },
        children: [
          {
            id: "title",
            label: "Title",
            type: "text",
            required: true,
            validation: [{ type: "maxLength", value: 40 }],
            permissions: {
              canView: ["creator", "approver", "admin"],
              canEdit: ["creator", "approver", "admin"],
              canApprove: ["approver", "admin"],
              canPublish: ["admin"],
            },
            ai: {
              aiEditable: true,
              aiGenerate: true,
              aiRewrite: true,
            },
            localisable: true,
          },
          {
            id: "text",
            label: "Text",
            type: "textarea",
            required: true,
            validation: [{ type: "maxLength", value: 140 }],
            permissions: {
              canView: ["creator", "approver", "admin"],
              canEdit: ["creator", "approver", "admin"],
              canApprove: ["approver", "admin"],
              canPublish: ["admin"],
            },
            ai: {
              aiEditable: true,
              aiGenerate: true,
              aiRewrite: true,
            },
            localisable: true,
          },
          {
            id: "accent",
            label: "Accent",
            type: "select",
            required: true,
            options: [
              { label: "Blue", value: "blue" },
              { label: "Green", value: "green" },
              { label: "Orange", value: "orange" },
              { label: "Purple", value: "purple" },
            ],
            validation: [
              {
                type: "allowedValues",
                value: ["blue", "green", "orange", "purple"],
              },
            ],
            permissions: {
              canView: ["creator", "approver", "admin"],
              canEdit: ["creator", "approver", "admin"],
              canApprove: ["approver", "admin"],
              canPublish: ["admin"],
            },
            ai: {
              aiEditable: false,
              aiGenerate: false,
              aiRewrite: false,
            },
            tokenBound: true,
            tokenReference: "color.accent",
          },
        ],
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "Reusable structured content component.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 2,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["items"],
      fieldMappings: [
        { sourceField: "sectionHeading", targetField: "sectionHeading" },
        { sourceField: "items", targetField: "items", required: true },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];