import type { ComponentSchema } from "@/lib/component-schema";

const now = new Date().toISOString();

const basePermissions = {
  canView: ["creator", "approver", "admin"] as const,
  canEdit: ["creator", "approver", "admin"] as const,
  canApprove: ["approver", "admin"] as const,
  canPublish: ["admin"] as const,
};

const editableAiRule = {
  aiEditable: true,
  aiGenerate: true,
  aiRewrite: true,
};

const lockedAiRule = {
  aiEditable: false,
  aiGenerate: false,
  aiRewrite: false,
};

export const COMPONENT_REGISTRY: ComponentSchema[] = [
  {
    id: "hero-standard",
    name: "Hero Standard",
    category: "hero",
    description:
      "Primary hero component for service and solution pages with headline, copy and CTA.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["core", "high-visibility", "top-of-page"],
    preview: {
      key: "hero",
      label: "Hero",
      style: "wireframe",
      aspectRatio: "wide",
    },
    useCaseLabel: "Top-of-page introduction",
    badges: ["Popular", "Core"],
    variants: [
      {
        id: "left-content-right-image",
        label: "Left Content / Right Image",
        description: "Split layout with content left and media right.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface"],
        preview: {
          key: "hero-split",
          label: "Split Hero",
          style: "wireframe",
          aspectRatio: "wide",
        },
        useCaseLabel: "Service pages",
        badges: ["Popular"],
      },
      {
        id: "centered",
        label: "Centered",
        description: "Centered hero for broader brand and campaign pages.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface", "tint"],
        preview: {
          key: "hero-centered",
          label: "Centered Hero",
          style: "wireframe",
          aspectRatio: "wide",
        },
        useCaseLabel: "Campaign pages",
        badges: ["Brand-led"],
      },
      {
        id: "with-stat-highlights",
        label: "With Stat Highlights",
        description: "Hero with supporting proof points or KPI highlights.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface", "tint"],
        preview: {
          key: "hero-stats",
          label: "Hero with Stats",
          style: "wireframe",
          aspectRatio: "wide",
        },
        useCaseLabel: "High-trust pages",
        badges: ["Proof-led"],
      },
      {
        id: "with-form",
        label: "With Form",
        description: "Conversion-focused hero with an embedded lead form area.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface"],
        preview: {
          key: "hero-form",
          label: "Hero with Form",
          style: "wireframe",
          aspectRatio: "wide",
        },
        useCaseLabel: "Lead generation",
        badges: ["Conversion"],
      },
    ],
    fields: [
      {
        id: "eyebrow",
        label: "Eyebrow",
        type: "text",
        placeholder: "Optional category label",
        validation: [{ type: "maxLength", value: 40 }],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Keep concise and credibility-led.",
        },
        localisable: true,
      },
      {
        id: "headline",
        label: "Headline",
        type: "text",
        required: true,
        placeholder: "Primary headline",
        validation: [{ type: "maxLength", value: 70 }],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Enterprise-grade, clear and non-hyped.",
        },
        localisable: true,
      },
      {
        id: "subheading",
        label: "Subheading",
        type: "textarea",
        required: true,
        placeholder: "Supporting paragraph",
        validation: [{ type: "maxLength", value: 180 }],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Support the headline with clear detail and credibility.",
        },
        localisable: true,
      },
      {
        id: "primaryCtaLabel",
        label: "Primary CTA Label",
        type: "text",
        required: true,
        validation: [{ type: "maxLength", value: 28 }],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Use approved CTA language only.",
        },
        localisable: true,
      },
      {
        id: "primaryCtaUrl",
        label: "Primary CTA URL",
        type: "url",
        required: true,
        validation: [{ type: "url" }],
        permissions: basePermissions,
        ai: lockedAiRule,
      },
      {
        id: "image",
        label: "Hero Image",
        type: "image",
        permissions: basePermissions,
        ai: lockedAiRule,
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "Primary high-visibility page component.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: ["hero-standard"],
      mustBeFirst: true,
      maxPerPage: 1,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: [
        "headline",
        "subheading",
        "primaryCtaLabel",
        "primaryCtaUrl",
      ],
      fieldMappings: [
        { sourceField: "eyebrow", targetField: "eyebrow" },
        { sourceField: "headline", targetField: "headline", required: true },
        { sourceField: "subheading", targetField: "subheading", required: true },
        {
          sourceField: "primaryCtaLabel",
          targetField: "primaryCtaLabel",
          required: true,
        },
        {
          sourceField: "primaryCtaUrl",
          targetField: "primaryCtaUrl",
          required: true,
        },
        { sourceField: "image", targetField: "image" },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },

  {
    id: "value-points-grid",
    name: "Value Points Grid",
    category: "content",
    description:
      "Structured value-point cards used to communicate service benefits or differentiators.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["core", "repeatable", "benefits"],
    preview: {
      key: "value-grid",
      label: "Value Grid",
      style: "wireframe",
      aspectRatio: "wide",
    },
    useCaseLabel: "Benefits and differentiators",
    badges: ["Core"],
    variants: [
      {
        id: "three-up",
        label: "3 Column Grid",
        description: "Three-card value point layout.",
        allowedLayouts: ["grid-3"],
        allowedBackgrounds: ["white", "surface"],
        preview: {
          key: "grid-3",
          label: "3 Up",
          style: "wireframe",
          aspectRatio: "wide",
        },
      },
      {
        id: "four-up",
        label: "4 Column Grid",
        description: "Four-card value point layout.",
        allowedLayouts: ["grid-4"],
        allowedBackgrounds: ["white", "surface"],
        preview: {
          key: "grid-4",
          label: "4 Up",
          style: "wireframe",
          aspectRatio: "wide",
        },
      },
      {
        id: "stacked-cards",
        label: "Stacked Cards",
        description: "Value points presented in a vertical card stack.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface", "tint"],
        preview: {
          key: "stacked-cards",
          label: "Stacked Cards",
          style: "wireframe",
          aspectRatio: "standard",
        },
      },
    ],
    fields: [
      {
        id: "sectionHeading",
        label: "Section Heading",
        type: "text",
        validation: [{ type: "maxLength", value: 70 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "items",
        label: "Value Points",
        type: "repeater",
        required: true,
        validation: [
          { type: "minItems", value: 3 },
          { type: "maxItems", value: 6 },
        ],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Keep each value point concise, distinct and benefits-led.",
        },
        children: [
          {
            id: "title",
            label: "Title",
            type: "text",
            required: true,
            validation: [{ type: "maxLength", value: 40 }],
            permissions: basePermissions,
            ai: editableAiRule,
            localisable: true,
          },
          {
            id: "text",
            label: "Text",
            type: "textarea",
            required: true,
            validation: [{ type: "maxLength", value: 140 }],
            permissions: basePermissions,
            ai: editableAiRule,
            localisable: true,
          },
          {
            id: "accent",
            label: "Accent",
            type: "select",
            required: true,
            options: [
              { label: "Blue", value: "blue" },
              { label: "Green", value: "green" },
              { label: "Orange", value: "orange" },
              { label: "Purple", value: "purple" },
            ],
            validation: [
              {
                type: "allowedValues",
                value: ["blue", "green", "orange", "purple"],
              },
            ],
            permissions: basePermissions,
            ai: lockedAiRule,
            tokenBound: true,
            tokenReference: "color.accent",
          },
        ],
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "Reusable structured content component.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 2,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["items"],
      fieldMappings: [
        { sourceField: "sectionHeading", targetField: "sectionHeading" },
        { sourceField: "items", targetField: "items", required: true },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },

  {
    id: "stats-band",
    name: "Stats Band",
    category: "proof",
    description:
      "Structured statistics section for trust, performance metrics and proof points.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["proof", "metrics", "trust"],
    preview: {
      key: "stats-band",
      label: "Stats Band",
      style: "wireframe",
      aspectRatio: "wide",
    },
    useCaseLabel: "Quantified proof",
    badges: ["Proof-led"],
    variants: [
      {
        id: "three-stats",
        label: "3 Stats",
        description: "Three evenly spaced statistics across a row.",
        allowedLayouts: ["grid-3"],
        allowedBackgrounds: ["white", "surface", "tint"],
      },
      {
        id: "four-stats",
        label: "4 Stats",
        description: "Four evenly spaced statistics across a row.",
        allowedLayouts: ["grid-4"],
        allowedBackgrounds: ["white", "surface", "tint"],
      },
      {
        id: "split-stat-callout",
        label: "Split Stat Callout",
        description: "One lead metric with supporting secondary stats.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface"],
      },
    ],
    fields: [
      {
        id: "sectionHeading",
        label: "Section Heading",
        type: "text",
        validation: [{ type: "maxLength", value: 70 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "stats",
        label: "Stats",
        type: "repeater",
        required: true,
        validation: [
          { type: "minItems", value: 3 },
          { type: "maxItems", value: 4 },
        ],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Use factual, concise, trust-building metrics only.",
        },
        children: [
          {
            id: "value",
            label: "Value",
            type: "text",
            required: true,
            validation: [{ type: "maxLength", value: 16 }],
            permissions: basePermissions,
            ai: editableAiRule,
          },
          {
            id: "label",
            label: "Label",
            type: "text",
            required: true,
            validation: [{ type: "maxLength", value: 40 }],
            permissions: basePermissions,
            ai: editableAiRule,
            localisable: true,
          },
          {
            id: "supportingText",
            label: "Supporting Text",
            type: "textarea",
            validation: [{ type: "maxLength", value: 100 }],
            permissions: basePermissions,
            ai: editableAiRule,
            localisable: true,
          },
        ],
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "Quantified proof claims should be reviewed before use.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 2,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["stats"],
      fieldMappings: [
        { sourceField: "sectionHeading", targetField: "sectionHeading" },
        { sourceField: "stats", targetField: "stats", required: true },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },

  {
    id: "testimonial-block",
    name: "Testimonial Block",
    category: "proof",
    description:
      "Customer quote and testimonial layouts for trust-building and social proof.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["proof", "social-proof", "trust"],
    preview: {
      key: "testimonial",
      label: "Testimonial",
      style: "wireframe",
      aspectRatio: "standard",
    },
    useCaseLabel: "Social proof",
    badges: ["Trust"],
    variants: [
      {
        id: "single-quote",
        label: "Single Quote",
        description: "Single featured testimonial with attribution.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface", "tint"],
      },
      {
        id: "quote-with-logo",
        label: "Quote With Logo",
        description: "Featured quote with supporting client logo or mark.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "two-up-testimonials",
        label: "2 Up Testimonials",
        description: "Two testimonials displayed side by side.",
        allowedLayouts: ["grid-2"],
        allowedBackgrounds: ["white", "surface"],
      },
    ],
    fields: [
      {
        id: "quote",
        label: "Quote",
        type: "textarea",
        required: true,
        validation: [{ type: "maxLength", value: 280 }],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Keep it specific, credible and outcome-focused.",
        },
        localisable: true,
      },
      {
        id: "authorName",
        label: "Author Name",
        type: "text",
        validation: [{ type: "maxLength", value: 60 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "authorRole",
        label: "Author Role",
        type: "text",
        validation: [{ type: "maxLength", value: 80 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "companyName",
        label: "Company Name",
        type: "text",
        validation: [{ type: "maxLength", value: 80 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "logo",
        label: "Client Logo",
        type: "image",
        permissions: basePermissions,
        ai: lockedAiRule,
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "External proof claims and named testimonials require review.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 3,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["quote"],
      fieldMappings: [
        { sourceField: "quote", targetField: "quote", required: true },
        { sourceField: "authorName", targetField: "authorName" },
        { sourceField: "authorRole", targetField: "authorRole" },
        { sourceField: "companyName", targetField: "companyName" },
        { sourceField: "logo", targetField: "logo" },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },

  {
    id: "logo-cloud",
    name: "Logo Cloud",
    category: "proof",
    description:
      "Trusted-by logo section for partner, customer or accreditation marks.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["proof", "logos", "trust"],
    preview: {
      key: "logo-cloud",
      label: "Logo Cloud",
      style: "wireframe",
      aspectRatio: "wide",
    },
    useCaseLabel: "Trusted by / accreditations",
    badges: ["Trust"],
    variants: [
      {
        id: "standard-grid",
        label: "Standard Grid",
        description: "Balanced grid of logos with optional heading.",
        allowedLayouts: ["grid"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "compact-strip",
        label: "Compact Strip",
        description: "Tighter row-based strip for subtle trust reinforcement.",
        allowedLayouts: ["row"],
        allowedBackgrounds: ["white", "surface", "tint"],
      },
      {
        id: "with-heading",
        label: "With Heading",
        description: "Logo cloud paired with a small supporting heading.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface"],
      },
    ],
    fields: [
      {
        id: "heading",
        label: "Heading",
        type: "text",
        validation: [{ type: "maxLength", value: 60 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "logos",
        label: "Logos",
        type: "repeater",
        required: true,
        validation: [
          { type: "minItems", value: 4 },
          { type: "maxItems", value: 12 },
        ],
        permissions: basePermissions,
        ai: lockedAiRule,
        children: [
          {
            id: "image",
            label: "Logo Image",
            type: "image",
            required: true,
            permissions: basePermissions,
            ai: lockedAiRule,
          },
          {
            id: "altText",
            label: "Alt Text",
            type: "text",
            validation: [{ type: "maxLength", value: 80 }],
            permissions: basePermissions,
            ai: editableAiRule,
            localisable: true,
          },
        ],
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "External brand and accreditation assets must be reviewed.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 2,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["logos"],
      fieldMappings: [
        { sourceField: "heading", targetField: "heading" },
        { sourceField: "logos", targetField: "logos", required: true },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },

  {
    id: "cta-banner",
    name: "CTA Banner",
    category: "conversion",
    description:
      "Focused conversion section for key calls to action and next-step prompts.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["conversion", "cta", "action"],
    preview: {
      key: "cta-banner",
      label: "CTA Banner",
      style: "wireframe",
      aspectRatio: "wide",
    },
    useCaseLabel: "Conversion prompt",
    badges: ["Conversion"],
    variants: [
      {
        id: "single-cta",
        label: "Single CTA",
        description: "Simple banner with one clear call to action.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["surface", "tint", "brand"],
      },
      {
        id: "dual-cta",
        label: "Dual CTA",
        description: "Banner with primary and secondary CTA actions.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["surface", "tint", "brand"],
      },
      {
        id: "cta-with-supporting-copy",
        label: "CTA With Supporting Copy",
        description: "Slightly richer CTA banner with added context.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["surface", "tint", "brand"],
      },
    ],
    fields: [
      {
        id: "heading",
        label: "Heading",
        type: "text",
        required: true,
        validation: [{ type: "maxLength", value: 80 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "body",
        label: "Body",
        type: "textarea",
        validation: [{ type: "maxLength", value: 180 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "primaryCtaLabel",
        label: "Primary CTA Label",
        type: "text",
        required: true,
        validation: [{ type: "maxLength", value: 28 }],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Use approved CTA language only.",
        },
        localisable: true,
      },
      {
        id: "primaryCtaUrl",
        label: "Primary CTA URL",
        type: "url",
        required: true,
        validation: [{ type: "url" }],
        permissions: basePermissions,
        ai: lockedAiRule,
      },
      {
        id: "secondaryCtaLabel",
        label: "Secondary CTA Label",
        type: "text",
        validation: [{ type: "maxLength", value: 28 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "secondaryCtaUrl",
        label: "Secondary CTA URL",
        type: "url",
        validation: [{ type: "url" }],
        permissions: basePermissions,
        ai: lockedAiRule,
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "Conversion-focused sections should use approved action language.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 3,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["heading", "primaryCtaLabel", "primaryCtaUrl"],
      fieldMappings: [
        { sourceField: "heading", targetField: "heading", required: true },
        { sourceField: "body", targetField: "body" },
        {
          sourceField: "primaryCtaLabel",
          targetField: "primaryCtaLabel",
          required: true,
        },
        {
          sourceField: "primaryCtaUrl",
          targetField: "primaryCtaUrl",
          required: true,
        },
        { sourceField: "secondaryCtaLabel", targetField: "secondaryCtaLabel" },
        { sourceField: "secondaryCtaUrl", targetField: "secondaryCtaUrl" },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },

  {
    id: "faq-section",
    name: "FAQ Section",
    category: "content",
    description:
      "Structured frequently asked questions section for objections, guidance and discoverability.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["faq", "content", "helpful"],
    preview: {
      key: "faq",
      label: "FAQ",
      style: "wireframe",
      aspectRatio: "standard",
    },
    useCaseLabel: "FAQs and objections",
    badges: ["Helpful"],
    variants: [
      {
        id: "accordion",
        label: "Accordion",
        description: "Expandable question-and-answer layout.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "two-column-faq",
        label: "2 Column FAQ",
        description: "Questions split across two columns.",
        allowedLayouts: ["grid-2"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "faq-with-intro",
        label: "FAQ With Intro",
        description: "FAQ section with supporting intro content above.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface", "tint"],
      },
    ],
    fields: [
      {
        id: "heading",
        label: "Heading",
        type: "text",
        validation: [{ type: "maxLength", value: 80 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "intro",
        label: "Intro",
        type: "textarea",
        validation: [{ type: "maxLength", value: 180 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "items",
        label: "FAQ Items",
        type: "repeater",
        required: true,
        validation: [
          { type: "minItems", value: 3 },
          { type: "maxItems", value: 10 },
        ],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Questions should be realistic and answers concise and helpful.",
        },
        children: [
          {
            id: "question",
            label: "Question",
            type: "text",
            required: true,
            validation: [{ type: "maxLength", value: 100 }],
            permissions: basePermissions,
            ai: editableAiRule,
            localisable: true,
          },
          {
            id: "answer",
            label: "Answer",
            type: "textarea",
            required: true,
            validation: [{ type: "maxLength", value: 280 }],
            permissions: basePermissions,
            ai: editableAiRule,
            localisable: true,
          },
        ],
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "FAQ content should remain accurate and brand-aligned.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 2,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["items"],
      fieldMappings: [
        { sourceField: "heading", targetField: "heading" },
        { sourceField: "intro", targetField: "intro" },
        { sourceField: "items", targetField: "items", required: true },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },

  {
    id: "media-text-split",
    name: "Media / Text Split",
    category: "media",
    description:
      "Flexible section combining supporting media with structured text content.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["media", "content", "flexible"],
    preview: {
      key: "media-split",
      label: "Media Split",
      style: "wireframe",
      aspectRatio: "wide",
    },
    useCaseLabel: "Content with supporting media",
    badges: ["Flexible"],
    variants: [
      {
        id: "image-left-content-right",
        label: "Image Left / Content Right",
        description: "Media on the left with supporting content on the right.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "content-left-image-right",
        label: "Content Left / Image Right",
        description: "Content on the left with media on the right.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "stacked-media-top",
        label: "Stacked / Media Top",
        description: "Media above the supporting content.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface", "tint"],
      },
    ],
    fields: [
      {
        id: "eyebrow",
        label: "Eyebrow",
        type: "text",
        validation: [{ type: "maxLength", value: 40 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "headline",
        label: "Headline",
        type: "text",
        required: true,
        validation: [{ type: "maxLength", value: 80 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "body",
        label: "Body",
        type: "textarea",
        required: true,
        validation: [{ type: "maxLength", value: 240 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "image",
        label: "Image",
        type: "image",
        permissions: basePermissions,
        ai: lockedAiRule,
      },
      {
        id: "primaryCtaLabel",
        label: "Primary CTA Label",
        type: "text",
        validation: [{ type: "maxLength", value: 28 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "primaryCtaUrl",
        label: "Primary CTA URL",
        type: "url",
        validation: [{ type: "url" }],
        permissions: basePermissions,
        ai: lockedAiRule,
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "Reusable mixed media section.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 4,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["headline", "body"],
      fieldMappings: [
        { sourceField: "eyebrow", targetField: "eyebrow" },
        { sourceField: "headline", targetField: "headline", required: true },
        { sourceField: "body", targetField: "body", required: true },
        { sourceField: "image", targetField: "image" },
        { sourceField: "primaryCtaLabel", targetField: "primaryCtaLabel" },
        { sourceField: "primaryCtaUrl", targetField: "primaryCtaUrl" },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },

  {
    id: "contact-form-section",
    name: "Contact Form Section",
    category: "conversion",
    description:
      "Lead capture or contact enquiry section with form-led structure.",
    status: "approved",
    visibility: "global",
    version: 1,
    schemaVersion: 1,
    ownerTeam: "Core Platform",
    tags: ["conversion", "form", "lead-gen"],
    preview: {
      key: "contact-form",
      label: "Contact Form",
      style: "wireframe",
      aspectRatio: "wide",
    },
    useCaseLabel: "Lead capture",
    badges: ["Conversion"],
    variants: [
      {
        id: "split-form",
        label: "Split Form",
        description: "Content alongside a structured form area.",
        allowedLayouts: ["split"],
        allowedBackgrounds: ["white", "surface"],
      },
      {
        id: "centered-form-card",
        label: "Centered Form Card",
        description: "Centered card layout focused on conversion.",
        allowedLayouts: ["stacked"],
        allowedBackgrounds: ["white", "surface", "tint"],
      },
      {
        id: "compact-form-strip",
        label: "Compact Form Strip",
        description: "Compressed enquiry form structure for faster actions.",
        allowedLayouts: ["row"],
        allowedBackgrounds: ["surface", "tint"],
      },
    ],
    fields: [
      {
        id: "heading",
        label: "Heading",
        type: "text",
        required: true,
        validation: [{ type: "maxLength", value: 80 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "body",
        label: "Body",
        type: "textarea",
        validation: [{ type: "maxLength", value: 180 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "formTitle",
        label: "Form Title",
        type: "text",
        validation: [{ type: "maxLength", value: 60 }],
        permissions: basePermissions,
        ai: editableAiRule,
        localisable: true,
      },
      {
        id: "submitLabel",
        label: "Submit Label",
        type: "text",
        validation: [{ type: "maxLength", value: 28 }],
        permissions: basePermissions,
        ai: {
          ...editableAiRule,
          promptHint: "Use clear, approved CTA wording.",
        },
        localisable: true,
      },
    ],
    approvals: {
      requiresApproval: true,
      approvalReason: "Form-led sections should align to approved conversion patterns.",
      requiresLegalReview: false,
      requiresRegionalReview: false,
      requiredApproverRoles: ["approver", "admin"],
    },
    composition: {
      allowedParents: ["page"],
      allowedChildren: [],
      cannotFollow: [],
      mustBeFirst: false,
      maxPerPage: 2,
      minPerPage: 0,
    },
    deployment: {
      deployable: true,
      targetCms: ["optimizely", "framer", "custom"],
      requiredMappings: ["heading"],
      fieldMappings: [
        { sourceField: "heading", targetField: "heading", required: true },
        { sourceField: "body", targetField: "body" },
        { sourceField: "formTitle", targetField: "formTitle" },
        { sourceField: "submitLabel", targetField: "submitLabel" },
      ],
      requiresPublishValidation: true,
      supportsLocales: true,
    },
    allowedLocales: ["en-GB", "en-US"],
    inheritsBrandRules: true,
    createdAt: now,
    updatedAt: now,
  },
];